# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-openapi-vapor:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-openapi-vapor:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -xcl "swift test --parallel -Xswiftc -warnings-as-errors $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
